# Generated by Django 5.2.5 on 2025-08-06 17:44

import django.db.models.deletion
import my_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', null=True)),
                ('skills', models.CharField(blank=True, choices=[('leadership', 'Leadership'), ('data_analysis', 'Data Analysis'), ('project_management', 'Project Management'), ('teamwork', 'Teamwork'), ('programming', 'Programming'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales')], max_length=50, null=True)),
                ('profession', models.CharField(blank=True, choices=[('financial_manager', 'Financial Manager'), ('it_manager', 'IT Manager'), ('software_developer', 'Software Developer'), ('physician_assistant', 'Physician Assistant'), ('marketing_manager', 'Marketing Manager'), ('sales_manager', 'Sales Manager'), ('designer', 'Designer'), ('consultant', 'Consultant')], max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=my_app.models.user_profile_picture_path)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=my_app.models.user_cover_photo_path)),
                ('profile_visibility', models.CharField(choices=[('only_me', 'Only Me'), ('followers', 'My Followers'), ('everyone', 'Everyone')], default='everyone', max_length=20)),
                ('show_email', models.BooleanField(default=False)),
                ('show_experiences', models.BooleanField(default=True)),
                ('show_followers', models.BooleanField(default=True)),
                ('who_can_tag', models.CharField(choices=[('everyone', 'Everyone'), ('group_member', 'Group Member')], default='everyone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
