# Generated by Django 5.2.5 on 2025-08-07 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Category Slug')),
                ('category_type', models.CharField(choices=[('main', 'MAIN'), ('apps', 'APPS'), ('pages', 'PAGES'), ('modules', 'MODULES'), ('others', 'OTHERS')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Menu Title')),
                ('slug', models.SlugField(max_length=200, verbose_name='Menu Slug')),
                ('url_name', models.CharField(blank=True, help_text='Django URL name or absolute URL', max_length=200, null=True, verbose_name='URL Name')),
                ('url_pattern', models.CharField(blank=True, help_text='URL pattern for active state checking', max_length=500, null=True, verbose_name='URL Pattern')),
                ('menu_type', models.CharField(choices=[('link', 'Direct Link'), ('dropdown', 'Dropdown Menu'), ('separator', 'Separator')], default='link', max_length=20)),
                ('icon_type', models.CharField(choices=[('material', 'Material Icons'), ('feather', 'Feather Icons'), ('custom', 'Custom Icon')], default='material', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Icon class or name (e.g., 'dashboard', 'shopping_cart')", max_length=100, verbose_name='Icon')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Badge Text')),
                ('badge_class', models.CharField(blank=True, default='hot tag', help_text='CSS classes for badge styling', max_length=100, verbose_name='Badge CSS Classes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('require_login', models.BooleanField(default=True, verbose_name='Require Login')),
                ('required_permissions', models.TextField(blank=True, help_text='Comma-separated list of required permissions', verbose_name='Required Permissions')),
                ('allowed_groups', models.TextField(blank=True, help_text='Comma-separated list of allowed user groups', verbose_name='Allowed Groups')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window'), ('_parent', 'Parent Frame'), ('_top', 'Top Frame')], default='_self', max_length=20, verbose_name='Link Target')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu_management.menucategory', verbose_name='Menu Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_menus', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_management.menuitem', verbose_name='Parent Menu')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__order', 'order', 'title'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='MenuLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('activate', 'Activated'), ('deactivate', 'Deactivated')], max_length=20)),
                ('description', models.TextField(verbose_name='Change Description')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Old Data')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='New Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='menu_management.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='menu_management.menuitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Menu Log',
                'verbose_name_plural': 'Menu Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Trezo', max_length=200, verbose_name='Site Name')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='menu/logos/', verbose_name='Site Logo')),
                ('logo_icon', models.CharField(default='/static/images/logo-icon.png', max_length=500, verbose_name='Logo Icon Path')),
                ('menu_style', models.CharField(choices=[('sidebar', 'Sidebar Menu'), ('horizontal', 'Horizontal Menu'), ('mixed', 'Mixed Layout')], default='sidebar', max_length=20)),
                ('collapse_menu', models.BooleanField(default=False, verbose_name='Collapse Menu by Default')),
                ('show_menu_icons', models.BooleanField(default=True, verbose_name='Show Menu Icons')),
                ('show_menu_badges', models.BooleanField(default=True, verbose_name='Show Menu Badges')),
                ('auto_close_dropdowns', models.BooleanField(default=True, verbose_name='Auto Close Dropdowns')),
                ('highlight_active_menu', models.BooleanField(default=True, verbose_name='Highlight Active Menu')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for menu styling', verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, help_text='Custom JavaScript for menu behavior', verbose_name='Custom JavaScript')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Menu Settings',
                'verbose_name_plural': 'Menu Settings',
            },
        ),
    ]
